#version: "3.9"

services:

  velocity:
    image: ghcr.io/mario-1981/velocity:latest
    container_name: velocity
    networks:
      - minecraft
    environment:
      PUID: 1000
      PGID: 1000
      JAVA_XMS: "1G"
      JAVA_XMX: "2G"
      JAVA_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled"
    ports:
      - "25565:25565"
    volumes:
      - velocity_data:/minecraft
    stdin_open: true
    tty: true

  paper:
    image: ghcr.io/mario-1981/minecraft-paper:latest
    container_name: paper
    networks:
      - minecraft
    environment:
      PUID: 1000
      PGID: 1000
#      EULA: "TRUE"        # muss explizit gesetzt werden!
      JAVA_XMS: "2G"
      JAVA_XMX: "4G"
      JAVA_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled"
    volumes:
      - paper_data:/minecraft
    stdin_open: true
    tty: true

volumes:
  paper_data:
  velocity_data:

networks:
  minecraft:
    driver: bridge
