#version: "3.9"

services:
  paper:
    image: ghcr.io/mario-1981/minecraft-folia:latest
    container_name: folia
    environment:
      PUID: 1000
      PGID: 1000
#      EULA: "TRUE"        # muss explizit gesetzt werden!
      JAVA_XMS: "2G"
      JAVA_XMX: "4G"
      JAVA_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled"
    ports:
      - "25565:25565"
    volumes:
      - ./folia_data:/minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
