#version: "3.9"

services:
  paper:
    image: ghcr.io/Mario-1981/minecraft-paper:1.21.8
    container_name: paper
    environment:
      EULA: "TRUE"        # muss explizit gesetzt werden!
      JAVA_XMS: "2G"
      JAVA_XMX: "4G"
      JAVA_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled"
    ports:
      - "25565:25565"
    volumes:
      - paper_data:/minecraft
    stdin_open: true
    tty: true

volumes:
  paper_data:
